export const topics: string[] = [
  "Animais",
  "Animais com penas",
  "Animais com pelos",
  "Animais com asas",
  "Animais invertebrados",
  "Répteis",
  "Anfíbios",
  "Mamíferos",
  "Insetos",
  "Espécies de peixes",
  "Espécies de felinos",
  "Raças de cachorro",
  "Animais aquáticos",
  "Animais terrestres",
  "Animais com chifres",
  "Animais com antenas",
  "Animais herbívoros",
  "Animais carnívoros",
  "Animais de estimação",
  "Animais venenosos",
  "Comidas",
  "Frutas",
  "Legumes e Verduras",
  "Temperos e especiarias",
  "Carboidratos",
  "Proteínas",
  "Laticínios",
  "Culinária Brasileira",
  "Culinária Asiática",
  "Culinária Europeia",
  "Comidas nordestinas",
  "Comidas de café da manhã",
  "Comidas de almoço",
  "Comidas de festa",
  "Comidas natalinas",
  "Comidas de Festa Junina",
  "Sobremesas",
  "Sobremesas brasileiras",
  "Doces e guloseimas",
  "Bebidas",
  "Sabores de pizza",
  "Sabores de sorvete",
  "Tipos de queijo",
  "Estados do mundo",
  "Países do mundo",
  "Capitais do mundo",
  "Capitais da Europa",
  "Capitais da América do Sul",
  "Estados do Brasil",
  "Capitais brasileiras",
  "Cidades do mundo",
  "Países da Europa",
  "Países da Ásia",
  "Países da África",
  "Países da Oceania",
  "Países da América",
  "Pontos turísticos brasileiros",
  "Pontos turísticos do mundo",
  "Tem no Parque de diversão",
  "Tem no shopping",
  "Tem no banheiro",
  "Tem no quarto",
  "Tem na cozinha",
  "Tem na escola",
  "Tem no restaurante",
  "Tem no natal",
  "Tem na geladeira",
  "Tem no mercado",
  "Tem no hospital",
  "Tem no carro",
  "Tem no circo",
  "Objetos",
  "Instrumentos musicais",
  "Eletrônicos",
  "Eletrodomésticos",
  "Materiais escolares",
  "Coisas com botão",
  "Coisas que emitem som",
  "Coisas de plástico",
  "Coisas de metal",
  "Coisas de vidro",
  "Coisas que usam pilha",
  "Coisas que giram",
  "Coisas que acendem",
  "Coisas que quebram fácil",
  "Coisas com fio",
  "Algo vermelho",
  "Algo quente",
  "Algo frio",
  "Algo perigoso",
  "Algo engraçado",
  "Algo nojento",
  "Algo valioso",
  "Algo inútil",
  "Algo assustador",
  "Algo feliz",
  "Algo redondo",
  "Algo quadrado",
  "Algo pontudo",
  "Algo pequeno",
  "Algo grande",
  "Algo invisível",
  "Algo com buracos",
  "Algo macio",
  "Algo que gruda",
  "Algo que você não gostaria de encontrar no escuro",
  "Coisas que flutuam na água",
  "Itens de vestuário",
  "Acessórios de moda",
  "Produtos de limpeza",
  "Itens de higiene pessoal",
  "Coisas que você abre",
  "Coisas com alça",
  "Brinquedos",
  "Jogos ou Brincadeiras",
  "Jogos de Video Game",
  "Tipos de tecido",
  "Cores",
  "Cores que não estão no arco-íris",
  "Nomes próprios",
  "Sobrenomes",
  "Nomes de pets",
  "Pessoas mais famosas do mundo",
  "Celebridades",
  "Personalidades históricas",
  "Criminosos famosos",
  "Sub-celebridades",
  "Diretores de cinema",
  "Atrizes",
  "Atores",
  "Celebridades da música",
  "Celebridades do esporte",
  "Celebridades da internet",
  "Celebridades brasileiras",
  "Celebridades americanas",
  "Celebridades latinas",
  "Celebridades europeias",
  "Celebridades que sumiram",
  "Celebridades que já morreram",
  "Celebridades brancas",
  "Celebridades negras",
  "Rappers famosos",
  "Cantores de pop",
  "Cantores de rock",
  "Celebridades polêmicas",
  "Bandas",
  "Políticos",
  "Ex BBBs",
  "Estrelas mirins",
  "Artistas plásticos famosos",
  "Personagens",
  "Personagens de filmes",
  "Personagens de séries",
  "Personagens de novelas",
  "Personagens de desenhos animados",
  "Personagens de animes",
  "Personagens de quadrinhos",
  "Personagens de jogos",
  "Personagens de terror",
  "Personagens de ficção científica",
  "Personagens bíblicos",
  "Super-heróis",
  "Contos de fadas",
  "Seres mitológicos",
  "Personagens com poderes mágicos",
  "Vilões",
  "Anti-heróis",
  "Protagonistas femininas em filmes ou séries",
  "Protagonistas infantis em filmes ou séries",
  "Personagens engraçados",
  "Personagens que morrem no final",
  "Mascotes de personagens principais",
  "Personagens de Harry Potter",
  "Personagens da Disney",
  "Personagens da Marvel",
  "Personagens da DC",
  "Personagens não humanos",
  "Personagens folclóricos",
  "Lendas urbanas",
  "Profissões",
  "Representa o Brasil",
  "Não tem no Brasil",
  "Tem nos Estados Unidos",
  "Tem na Asía",
  "Tem na Europa",
  "Onde esconder um corpo",
  "Nacionalidades",
  "Marcas",
  "Marcas que usamos todo dia",
  "Redes sociais",
  "Aplicativos",
  "Marcas de luxo",
  "Marcas de eletrônicos",
  "Esportes",
  "Esportes sem bola",
  "Carros",
  "Elogios",
  "Sentimentos",
  "Partes do corpo humano",
  "Órgãos do corpo humano",
  "Times de futebol",
  "Times de futebol brasileiros",
  "Meios de transporte",
  "Verbos",
  "Deveria ser crime",
  "Pior presente de aniversário",
  "No meu casamento vai ter...",
  "Superpoderes",
  "Antes de morrer quero...",
  "O que fazer ao me encontrar com um alienígena",
  "Medo de...",
  "Manias estranhas",
  "Música que acaba com qualquer festa",
  "Músicas famosas",
  "Músicas infantis",
  "Não me orgulho de...",
  "Queria ter...",
  "Título para uma novela nova",
  "Nomes de Presidentes",
  "Frutas em inglês",
  "Objetos em inglês",
  "Animais em inglês",
  "Objetos Inúteis em Casa",
  "Coisas que fazíamos na infância",
  "Coisas inúteis para se ter no espaço",
  "O que não fazer em um primeiro encontro",
  "Minha sogra é...",
  "Acho chique",
  "Acho cafona",
  "Se tivesse dinheiro eu...",
  "Fiz e faria de novo",
  "Vocativos de garçom",
  "Gênero Musical",
  "White people problem",
  "Eu seria cancelado por...",
  "Luxo de pobre",
  "Xingamentos",
  "Vergonha alheia",
  "Motivos pra fazer terapia",
  "Pequenos prazeres da vida",
  "Não pode faltar na minha playlist...",
  "Artistas sem talento",
  "Elementos da tabela periódica",
  "Sou pobre mas...",
  "Micos que alguém pode pagar",
  "Coisas que não existem mais",
  "Gírias ou expressões",
  "Motivos para levar bronca",
  "Motivos para ser demitido",
  "Motivos para ser preso",
  "Algo que você faria se fosse um vilão",
  "Algo que você faria se ficasse invisível",
  "Nome da sua banda de rock",
  "Algo não comestível que você comeria",
  "Filmes",
  "Irrita qualquer pessoa",
  "Invenções humanas",
  "Palavras que sejam um palíndromo",
  "Palavras com mais de três sílabas",
  "Palavras com duas sílabas",
  "Palavras com duplo sentido",
  "Descoberta científica",
  "Superpoder bizarro",
  "Coisas que cabem no bolso",
  "Algo que você usaria como chapéu",
  "Algo que você nunca emprestaria",
  "Algo que você levaria para uma ilha deserta",
  "Coisas que te deixam com vergonha",
  "Séries",
  "Séries adolescentes",
  "Desenhos animados",
  "Animes",
  "Programas de TV",
  "Programas de TV Brasileiros",
  "Pior Filme da História",
  "Melhor Filme da História",
  "Filmes ou Séries de ação",
  "Filmes ou Séries de comédia",
  "Filmes ou Séries de terror",
  "Filmes românticos",
  "Filmes musicais",
  "Filmes ou Séries de animação",
  "Filmes ou Séries baseados em fatos reais",
  "Filmes ou Séries lançados recentemente",
  "Filmes brasileiros",
  "Franquias de Filmes",
  "Filmes ou Séries clássicos",
  "Filmes ou Séries infantis",
  "Filmes indicados ao Oscar",
  "Filmes baseados em livros",
  "Filmes ou Séries com protagonista feminina",
  "Doenças",
  "Doenças contagiosas",
  "Doenças genéticas",
  "Alergias",
  "Fobias",
  "Doenças que têm vacina",
  "Medicamentos",
  "Procedimentos cirúrgicos",
  "Distúrbios ou Transtornos",
  "Espécies de Flores",
  "Plantas medicinais",
  "Árvores frutíferas",
  "Espécies de árvores",
  "Fenomenos da natureza",
    "Animais",
  "Animais com penas",
  "Animais com pelos",
  "Animais com asas",
  "Animais invertebrados",
  "Répteis",
  "Anfíbios",
  "Mamíferos",
  "Insetos",
  "Espécies de peixes",
  "Espécies de felinos",
  "Raças de cachorro",
  "Animais aquáticos",
  "Animais terrestres",
  "Animais com chifres",
  "Animais com antenas",
  "Animais herbívoros",
  "Animais carnívoros",
  "Animais de estimação",
  "Animais venenosos",
  "Comidas",
  "Frutas",
  "Legumes e Verduras",
  "Temperos e especiarias",
  "Carboidratos",
  "Proteínas",
  "Laticínios",
  "Culinária Brasileira",
  "Culinária Asiática",
  "Culinária Europeia",
  "Comidas nordestinas",
  "Comidas de café da manhã",
  "Comidas de almoço",
  "Comidas de festa",
  "Comidas natalinas",
  "Comidas de Festa Junina",
  "Sobremesas",
  "Sobremesas brasileiras",
  "Doces e guloseimas",
  "Bebidas",
  "Sabores de pizza",
  "Sabores de sorvete",
  "Tipos de queijo",
  "Estados do mundo",
  "Países do mundo",
  "Capitais do mundo",
  "Capitais da Europa",
  "Capitais da América do Sul",
  "Estados do Brasil",
  "Capitais brasileiras",
  "Cidades do mundo",
  "Países da Europa",
  "Países da Ásia",
  "Países da África",
  "Países da Oceania",
  "Países da América",
  "Pontos turísticos brasileiros",
  "Pontos turísticos do mundo",
  "Tem no Parque de diversão",
  "Tem no shopping",
  "Tem no banheiro",
  "Tem no quarto",
  "Tem na cozinha",
  "Tem na escola",
  "Tem no restaurante",
  "Tem no natal",
  "Tem na geladeira",
  "Tem no mercado",
  "Tem no hospital",
  "Tem no carro",
  "Tem no circo",
  "Objetos",
  "Instrumentos musicais",
  "Eletrônicos",
  "Eletrodomésticos",
  "Materiais escolares",
  "Coisas com botão",
  "Coisas que emitem som",
  "Coisas de plástico",
  "Coisas de metal",
  "Coisas de vidro",
  "Coisas que usam pilha",
  "Coisas que giram",
  "Coisas que acendem",
  "Coisas que quebram fácil",
  "Coisas com fio",
  "Algo vermelho",
  "Algo quente",
  "Algo frio",
  "Algo perigoso",
  "Algo engraçado",
  "Algo nojento",
  "Algo valioso",
  "Algo inútil",
  "Algo assustador",
  "Algo feliz",
  "Algo redondo",
  "Algo quadrado",
  "Algo pontudo",
  "Algo pequeno",
  "Algo grande",
  "Algo invisível",
  "Algo com buracos",
  "Algo macio",
  "Algo que gruda",
  "Algo que você não gostaria de encontrar no escuro",
  "Coisas que flutuam na água",
  "Itens de vestuário",
  "Acessórios de moda",
  "Produtos de limpeza",
  "Itens de higiene pessoal",
  "Coisas que você abre",
  "Coisas com alça",
  "Brinquedos",
  "Jogos ou Brincadeiras",
  "Jogos de Video Game",
  "Tipos de tecido",
  "Cores",
  "Cores que não estão no arco-íris",
  "Nomes próprios",
  "Sobrenomes",
  "Nomes de pets",
  "Pessoas mais famosas do mundo",
  "Celebridades",
  "Personalidades históricas",
  "Criminosos famosos",
  "Sub-celebridades",
  "Diretores de cinema",
  "Atrizes",
  "Atores",
  "Celebridades da música",
  "Celebridades do esporte",
  "Celebridades da internet",
  "Celebridades brasileiras",
  "Celebridades americanas",
  "Celebridades latinas",
  "Celebridades europeias",
  "Celebridades que sumiram",
  "Celebridades que já morreram",
  "Celebridades brancas",
  "Celebridades negras",
  "Rappers famosos",
  "Cantores de pop",
  "Cantores de rock",
  "Celebridades polêmicas",
  "Bandas",
  "Políticos",
  "Ex BBBs",
  "Estrelas mirins",
  "Artistas plásticos famosos",
  "Personagens",
  "Personagens de filmes",
  "Personagens de séries",
  "Personagens de novelas",
  "Personagens de desenhos animados",
  "Personagens de animes",
  "Personagens de quadrinhos",
  "Personagens de jogos",
  "Personagens de terror",
  "Personagens de ficção científica",
  "Personagens bíblicos",
  "Super-heróis",
  "Contos de fadas",
  "Seres mitológicos",
  "Personagens com poderes mágicos",
  "Vilões",
  "Anti-heróis",
  "Protagonistas femininas em filmes ou séries",
  "Protagonistas infantis em filmes ou séries",
  "Personagens engraçados",
  "Personagens que morrem no final",
  "Mascotes de personagens principais",
  "Personagens de Harry Potter",
  "Personagens da Disney",
  "Personagens da Marvel",
  "Personagens da DC",
  "Personagens não humanos",
  "Personagens folclóricos",
  "Lendas urbanas",
  "Profissões",
  "Representa o Brasil",
  "Não tem no Brasil",
  "Tem nos Estados Unidos",
  "Tem na Asía",
  "Tem na Europa",
  "Onde esconder um corpo",
  "Nacionalidades",
  "Marcas",
  "Marcas que usamos todo dia",
  "Redes sociais",
  "Aplicativos",
  "Marcas de luxo",
  "Marcas de eletrônicos",
  "Esportes",
  "Esportes sem bola",
  "Carros",
  "Elogios",
  "Sentimentos",
  "Partes do corpo humano",
  "Órgãos do corpo humano",
  "Times de futebol",
  "Times de futebol brasileiros",
  "Meios de transporte",
  "Verbos",
  "Deveria ser crime",
  "Pior presente de aniversário",
  "No meu casamento vai ter...",
  "Superpoderes",
  "Antes de morrer quero...",
  "O que fazer ao me encontrar com um alienígena",
  "Medo de...",
  "Manias estranhas",
  "Música que acaba com qualquer festa",
  "Músicas famosas",
  "Músicas infantis",
  "Não me orgulho de...",
  "Queria ter...",
  "Título para uma novela nova",
  "Nomes de Presidentes",
  "Frutas em inglês",
  "Objetos em inglês",
  "Animais em inglês",
  "Objetos Inúteis em Casa",
  "Coisas que fazíamos na infância",
  "Coisas inúteis para se ter no espaço",
  "O que não fazer em um primeiro encontro",
  "Minha sogra é...",
  "Acho chique",
  "Acho cafona",
  "Se tivesse dinheiro eu...",
  "Fiz e faria de novo",
  "Vocativos de garçom",
  "Gênero Musical",
  "White people problem",
  "Eu seria cancelado por...",
  "Luxo de pobre",
  "Xingamentos",
  "Vergonha alheia",
  "Motivos pra fazer terapia",
  "Pequenos prazeres da vida",
  "Não pode faltar na minha playlist...",
  "Artistas sem talento",
  "Elementos da tabela periódica",
  "Sou pobre mas...",
  "Micos que alguém pode pagar",
  "Coisas que não existem mais",
  "Gírias ou expressões",
  "Motivos para levar bronca",
  "Motivos para ser demitido",
  "Motivos para ser preso",
  "Algo que você faria se fosse um vilão",
  "Algo que você faria se ficasse invisível",
  "Nome da sua banda de rock",
  "Algo não comestível que você comeria",
  "Filmes",
  "Irrita qualquer pessoa",
  "Invenções humanas",
  "Palavras que sejam um palíndromo",
  "Palavras com mais de três sílabas",
  "Palavras com duas sílabas",
  "Palavras com duplo sentido",
  "Descoberta científica",
  "Superpoder bizarro",
  "Coisas que cabem no bolso",
  "Algo que você usaria como chapéu",
  "Algo que você nunca emprestaria",
  "Algo que você levaria para uma ilha deserta",
  "Coisas que te deixam com vergonha",
  "Séries",
  "Séries adolescentes",
  "Desenhos animados",
  "Animes",
  "Programas de TV",
  "Programas de TV Brasileiros",
  "Pior Filme da História",
  "Melhor Filme da História",
  "Filmes ou Séries de ação",
  "Filmes ou Séries de comédia",
  "Filmes ou Séries de terror",
  "Filmes românticos",
  "Filmes musicais",
  "Filmes ou Séries de animação",
  "Filmes ou Séries baseados em fatos reais",
  "Filmes ou Séries lançados recentemente",
  "Filmes brasileiros",
  "Franquias de Filmes",
  "Filmes ou Séries clássicos",
  "Filmes ou Séries infantis",
  "Filmes indicados ao Oscar",
  "Filmes baseados em livros",
  "Filmes ou Séries com protagonista feminina",
  "Doenças",
  "Doenças contagiosas",
  "Doenças genéticas",
  "Alergias",
  "Fobias",
  "Doenças que têm vacina",
  "Medicamentos",
  "Procedimentos cirúrgicos",
  "Distúrbios ou Transtornos",
  "Espécies de Flores",
  "Plantas medicinais",
  "Árvores frutíferas",
  "Espécies de árvores",
  "Fenomenos da natureza",
];

export const alfa: string[] = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "X",
  "Z",
];
